In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40 50]


In [3]:
import numpy as np
a=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print("Two dimensional array:",a)

Two dimensional array: [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
import numpy as np
a=np.zeros((3,5))
print("\n Array with all zeros:\n",a)


 Array with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random value:",d)


 Random value: [[0.87946757 0.63090292 0.82874805]
 [0.12252681 0.2624025  0.02962696]
 [0.7313993  0.87696721 0.11412588]]


In [7]:
import numpy as np
e=np.arange(0,10,1)
print("\n Range value :\n",e)


 Range value :
 [0 1 2 3 4 5 6 7 8 9]


In [8]:
import numpy as np
e=np.arange(0,10,5)
print("\n Range value :\n",e)


 Range value :
 [0 5]


In [1]:
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape((4,3))
print("\n Original array:",arr)
print("\n Reshaped array:",newarr)
newtype=arr.astype('f')
print("converted array element:\n",newtype)
print("converted array:" ,newtype.dtype)
size=len(arr)
print("\n size of array:\n",size)


 Original array: [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 Reshaped array: [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]
converted array element:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
converted array: float32

 size of array:
 3


In [1]:
import numpy as np
a=np.zeros((5,3))
print("\n Array with 5x3 with all zeros:\n",a)


 Array with 5x3 with all zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np
a=np.random.random((5,3))
print("\n Array with 5x3 with all Random Numbers:\n",a)


 Array with 5x3 with all Random Numbers:
 [[0.56347699 0.00142372 0.34454864]
 [0.45750291 0.77197486 0.72972187]
 [0.41213894 0.61247472 0.24462655]
 [0.97781793 0.35785797 0.99369307]
 [0.8228994  0.77176082 0.41449275]]


In [12]:
import numpy as np
arr=np.array([[0.56347699, 0.00142372, 0.34454864],
[0.45750291,0.77197486, 0.72972187],
[0.41213894, 0.61247472, 0.24462655],
[0.97781793, 0.35785797, 0.99369307],
[0.8228994,  0.77176082, 0.41449275]])
newarr=arr.reshape((3,5))
print("\n Original array:",arr)
print("\n Reshaped array:",newarr)


 Original array: [[0.56347699 0.00142372 0.34454864]
 [0.45750291 0.77197486 0.72972187]
 [0.41213894 0.61247472 0.24462655]
 [0.97781793 0.35785797 0.99369307]
 [0.8228994  0.77176082 0.41449275]]

 Reshaped array: [[0.56347699 0.00142372 0.34454864 0.45750291 0.77197486]
 [0.72972187 0.41213894 0.61247472 0.24462655 0.97781793]
 [0.35785797 0.99369307 0.8228994  0.77176082 0.41449275]]


In [4]:
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape((4,3))
print("\n Original array:",arr)
print("\n Reshaped array:",newarr)
print("\n No. of diminsions: ",arr.ndim)


 Original array: [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 Reshaped array: [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]

 No. of diminsions:  2


In [11]:
flat=arr.flatten()
print("Flattened Array: \n",flat)

Flattened Array: 
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [6]:
print("\n Shape of array :",arr.shape)


 Shape of array : (3, 4)
